# The configuration file for MMDBot

# For most keys, if it is left blank or an invalid value, the corresponding feature is disabled or cannot output

[bot.activity]
# The type of activity the bot has.
type = "PLAYING"

# The name of the activity the bot has.
name = "the watching game"
